import type { Hex } from "../coordinates.js";
import {
  BASE_HARBOR_TYPE_SEQUENCE,
  BASE_NUMBER_TOKEN_BAG,
  BASE_TERRAIN_BAG,
  type BoardSpec,
} from "../board/generate.js";
import type { HarborType, TerrainType } from "../types.js";

/**
 * A Seafarers-style map. `knownHexes`/`knownTerrainBag`/`knownNumberBag`/
 * `harborTypes` are shaped exactly like {@link BoardSpec} (see
 * `boardSpecForScenario` below) — the known portion of the map is
 * generated by the same shuffle-and-place algorithm as the base board,
 * just scoped to the scenario's own hex list and bag, keeping harbor
 * placement fixed the same way base's is. `hiddenLandHexes` start
 * face-down and are revealed from `discoveryBag` during play — see
 * docs/rules/seafarers-style.md.
 */
export interface ScenarioDefinition {
  readonly id: string;
  readonly recommendedPlayers: readonly [min: number, max: number];
  readonly knownHexes: readonly Hex[];
  readonly knownTerrainBag: readonly TerrainType[];
  readonly knownNumberBag: readonly number[];
  readonly harborTypes: readonly HarborType[];
  readonly hiddenLandHexes: readonly Hex[];
  /** Shuffled at game start; length must equal `hiddenLandHexes.length`. */
  readonly discoveryBag: readonly { terrain: TerrainType; number: number | null }[];
  readonly seaHexes: readonly Hex[];
  readonly pirateStartHex: Hex;
  /** Never eligible for the island-settlement VP bonus. */
  readonly homeIslandHexes: readonly Hex[];
}

/** The `BoardSpec` for a scenario's known (non-hidden) portion. */
export function boardSpecForScenario(scenario: ScenarioDefinition): BoardSpec {
  return {
    hexes: scenario.knownHexes,
    terrainBag: scenario.knownTerrainBag,
    numberBag: scenario.knownNumberBag,
    harborTypes: scenario.harborTypes,
  };
}

// --- Twin Isles (2-4 players) --------------------------------------------
// Two equal 7-hex islands (radius-1 hexagons, centers 4 apart) — closest
// land-to-land distance 2, a single hex of open sea between their nearest
// coasts. Both islands are fully known (too small to hide either without
// making the game too swingy); the "other" island is the sole bonus
// target. 14 known land + 21 sea = 35 hexes total.

const TWIN_ISLES_HOME_ISLAND: readonly Hex[] = [
  { q: -1, r: 0 },
  { q: -1, r: 1 },
  { q: 0, r: -1 },
  { q: 0, r: 0 },
  { q: 0, r: 1 },
  { q: 1, r: -1 },
  { q: 1, r: 0 },
];

const TWIN_ISLES_OTHER_ISLAND: readonly Hex[] = [
  { q: 3, r: -2 },
  { q: 3, r: -1 },
  { q: 4, r: -3 },
  { q: 4, r: -2 },
  { q: 4, r: -1 },
  { q: 5, r: -3 },
  { q: 5, r: -2 },
];

const TWIN_ISLES_SEA: readonly Hex[] = [
  { q: -2, r: 0 },
  { q: -2, r: 1 },
  { q: -2, r: 2 },
  { q: -1, r: -1 },
  { q: -1, r: 2 },
  { q: 0, r: -2 },
  { q: 0, r: 2 },
  { q: 1, r: -2 },
  { q: 1, r: 1 },
  { q: 2, r: -2 },
  { q: 2, r: -1 },
  { q: 2, r: 0 },
  { q: 3, r: -3 },
  { q: 3, r: 0 },
  { q: 4, r: -4 },
  { q: 4, r: 0 },
  { q: 5, r: -4 },
  { q: 5, r: -1 },
  { q: 6, r: -4 },
  { q: 6, r: -3 },
  { q: 6, r: -2 },
];

export const TWIN_ISLES: ScenarioDefinition = {
  id: "twin-isles",
  recommendedPlayers: [2, 4],
  knownHexes: [...TWIN_ISLES_HOME_ISLAND, ...TWIN_ISLES_OTHER_ISLAND],
  knownTerrainBag: [
    "wood",
    "wood",
    "wood",
    "wheat",
    "wheat",
    "wheat",
    "sheep",
    "sheep",
    "sheep",
    "brick",
    "brick",
    "ore",
    "ore",
    "desert",
  ],
  knownNumberBag: [2, 3, 3, 4, 5, 5, 6, 8, 9, 9, 10, 11, 12],
  harborTypes: ["generic", "ore", "generic", "wheat", "sheep", "generic"],
  hiddenLandHexes: [],
  discoveryBag: [],
  seaHexes: TWIN_ISLES_SEA,
  pirateStartHex: { q: 2, r: -1 },
  homeIslandHexes: TWIN_ISLES_HOME_ISLAND,
};

// --- The Strait (2-4 players) ---------------------------------------------
// The base 19-hex board (fully known, identical layout/bag/harbors to
// base) plus a 7-hex secondary island (hidden), centers 5 apart — closest
// land-to-land distance 2, a single-hex-wide strait. 26 land + 12 sea = 38
// hexes.

const THE_STRAIT_HOME_ISLAND: readonly Hex[] = [
  { q: -2, r: 0 },
  { q: -2, r: 1 },
  { q: -2, r: 2 },
  { q: -1, r: -1 },
  { q: -1, r: 0 },
  { q: -1, r: 1 },
  { q: -1, r: 2 },
  { q: 0, r: -2 },
  { q: 0, r: -1 },
  { q: 0, r: 0 },
  { q: 0, r: 1 },
  { q: 0, r: 2 },
  { q: 1, r: -2 },
  { q: 1, r: -1 },
  { q: 1, r: 0 },
  { q: 1, r: 1 },
  { q: 2, r: -2 },
  { q: 2, r: -1 },
  { q: 2, r: 0 },
];

const THE_STRAIT_SECONDARY_ISLAND: readonly Hex[] = [
  { q: 4, r: 0 },
  { q: 4, r: 1 },
  { q: 5, r: -1 },
  { q: 5, r: 0 },
  { q: 5, r: 1 },
  { q: 6, r: -1 },
  { q: 6, r: 0 },
];

const THE_STRAIT_SEA: readonly Hex[] = [
  { q: 3, r: 0 },
  { q: 3, r: 1 },
  { q: 3, r: 2 },
  { q: 4, r: -1 },
  { q: 4, r: 2 },
  { q: 5, r: -2 },
  { q: 5, r: 2 },
  { q: 6, r: -2 },
  { q: 6, r: 1 },
  { q: 7, r: -2 },
  { q: 7, r: -1 },
  { q: 7, r: 0 },
];

export const THE_STRAIT: ScenarioDefinition = {
  id: "the-strait",
  recommendedPlayers: [2, 4],
  knownHexes: THE_STRAIT_HOME_ISLAND,
  knownTerrainBag: BASE_TERRAIN_BAG,
  knownNumberBag: BASE_NUMBER_TOKEN_BAG,
  harborTypes: BASE_HARBOR_TYPE_SEQUENCE,
  hiddenLandHexes: THE_STRAIT_SECONDARY_ISLAND,
  discoveryBag: [
    { terrain: "wood", number: 4 },
    { terrain: "wood", number: 5 },
    { terrain: "wheat", number: 6 },
    { terrain: "sheep", number: 9 },
    { terrain: "brick", number: 10 },
    { terrain: "ore", number: 11 },
    { terrain: "desert", number: null },
  ],
  seaHexes: THE_STRAIT_SEA,
  pirateStartHex: { q: 3, r: 0 },
  homeIslandHexes: THE_STRAIT_HOME_ISLAND,
};

// --- Scattered Archipelago (4-6 players — pairs with five-six-players) ---
// The base 19-hex board (fully known) plus three 3-hex satellite islands
// (all hidden), each well-separated from the home island and from each
// other. 28 land + 48 sea = 76 hexes.

const SATELLITE_1: readonly Hex[] = [
  { q: 5, r: -2 },
  { q: 6, r: -3 },
  { q: 5, r: -3 },
];

const SATELLITE_2: readonly Hex[] = [
  { q: -2, r: 5 },
  { q: -3, r: 6 },
  { q: -2, r: 6 },
];

const SATELLITE_3: readonly Hex[] = [
  { q: -4, r: -1 },
  { q: -4, r: -2 },
  { q: -5, r: -1 },
];

const SCATTERED_ARCHIPELAGO_SEA: readonly Hex[] = [
  { q: 3, r: -2 },
  { q: 3, r: -1 },
  { q: 3, r: 0 },
  { q: 4, r: -3 },
  { q: 4, r: -2 },
  { q: 4, r: -1 },
  { q: 4, r: 0 },
  { q: 5, r: -4 },
  { q: 5, r: -1 },
  { q: 5, r: 0 },
  { q: 6, r: -4 },
  { q: 6, r: -2 },
  { q: 6, r: -1 },
  { q: 7, r: -4 },
  { q: 7, r: -3 },
  { q: 7, r: -2 },
  { q: -4, r: 5 },
  { q: -4, r: 6 },
  { q: -4, r: 7 },
  { q: -3, r: 4 },
  { q: -3, r: 5 },
  { q: -3, r: 7 },
  { q: -2, r: 3 },
  { q: -2, r: 4 },
  { q: -2, r: 7 },
  { q: -1, r: 3 },
  { q: -1, r: 4 },
  { q: -1, r: 5 },
  { q: -1, r: 6 },
  { q: 0, r: 3 },
  { q: 0, r: 4 },
  { q: 0, r: 5 },
  { q: -6, r: -1 },
  { q: -6, r: 0 },
  { q: -6, r: 1 },
  { q: -5, r: -2 },
  { q: -5, r: 0 },
  { q: -5, r: 1 },
  { q: -4, r: -3 },
  { q: -4, r: 0 },
  { q: -4, r: 1 },
  { q: -3, r: -3 },
  { q: -3, r: -2 },
  { q: -3, r: -1 },
  { q: -3, r: 0 },
  { q: -2, r: -3 },
  { q: -2, r: -2 },
  { q: -2, r: -1 },
];

export const SCATTERED_ARCHIPELAGO: ScenarioDefinition = {
  id: "scattered-archipelago",
  recommendedPlayers: [4, 6],
  knownHexes: THE_STRAIT_HOME_ISLAND, // identical 19-hex home layout
  knownTerrainBag: BASE_TERRAIN_BAG,
  knownNumberBag: BASE_NUMBER_TOKEN_BAG,
  harborTypes: BASE_HARBOR_TYPE_SEQUENCE,
  hiddenLandHexes: [...SATELLITE_1, ...SATELLITE_2, ...SATELLITE_3],
  discoveryBag: [
    { terrain: "wood", number: 3 },
    { terrain: "wood", number: 4 },
    { terrain: "wheat", number: 5 },
    { terrain: "wheat", number: 6 },
    { terrain: "sheep", number: 8 },
    { terrain: "sheep", number: 9 },
    { terrain: "brick", number: 10 },
    { terrain: "ore", number: 11 },
    { terrain: "desert", number: null },
  ],
  seaHexes: SCATTERED_ARCHIPELAGO_SEA,
  pirateStartHex: { q: 3, r: -2 },
  homeIslandHexes: THE_STRAIT_HOME_ISLAND,
};
